# Generated by Django 3.1 on 2020-08-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20200828_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeimages',
            name='owner',
        ),
    ]
