# Generated by Django 3.1 on 2020-08-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_remove_homeimages_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_image',
            field=models.ImageField(null=True, upload_to='home_images'),
        ),
    ]
