# Generated by Django 3.1 on 2020-08-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_post_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='main_image',
        ),
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='floor_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='rooms',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='post',
            name='town',
            field=models.TextField(null=True),
        ),
    ]
