# Generated by Django 3.1 on 2020-08-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_post_display_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='post',
            name='display_image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='home_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.TextField(default=0),
        ),
    ]
