# Generated by Django 3.1 on 2020-09-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20200831_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gallery_image_0',
            field=models.ImageField(null=True, upload_to='home_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='gallery_image_1',
            field=models.ImageField(null=True, upload_to='home_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='gallery_image_2',
            field=models.ImageField(null=True, upload_to='home_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='gallery_image_3',
            field=models.ImageField(null=True, upload_to='home_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='display_image',
            field=models.ImageField(default='default_home.png', upload_to='home_images'),
        ),
        migrations.DeleteModel(
            name='HomeImages',
        ),
    ]
