# Generated by Django 3.1 on 2020-09-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20200925_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='flat_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='floor_area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='remaining_lease',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='gallery_image_0',
            field=models.ImageField(default='default_home.png', null=True, upload_to='home_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='gallery_image_1',
            field=models.ImageField(default='default_home.png', null=True, upload_to='home_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='gallery_image_2',
            field=models.ImageField(default='default_home.png', null=True, upload_to='home_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='gallery_image_3',
            field=models.ImageField(default='default_home.png', null=True, upload_to='home_images'),
        ),
    ]
