# Generated by Django 3.1 on 2020-09-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_auto_20200927_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recommended_price',
            field=models.TextField(null=True),
        ),
    ]
