# Generated by Django 3.1 on 2020-09-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_auto_20200927_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='flat_type',
            field=models.CharField(choices=[('Studio Apartment', 'Studio Apartment'), ('2-Room Flat', '2-Room Flat'), ('3-Room Flat', '3-Room Flat'), ('4-Room Flat', '4-Room Flat'), ('5-Room Flat', '5-Room Flat'), ('Executive Flat', 'Executive Flat')], default='2-Room Flat', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='town',
            field=models.CharField(choices=[('ANG MO KIO', 'ANG MO KIO'), ('BEDOK', 'BEDOK'), ('BISHAN', 'BISHAN'), ('BUKIT MERAH', 'BUKIT MERAH'), ('BUKIT BATOK', 'BUKIT BATOK'), ('CENTRAL AREA', 'CENTRAL AREA'), ('BUKIT PANJANG', 'BUKIT PANJANG'), ('GEYLANG', 'GEYLANG'), ('BUKIT TIMAH', 'BUKIT TIMAH'), ('CHOA CHU KANG', 'CHOA CHU KANG'), ('CLEMENTI', 'CLEMENTI'), ('HOUGANG', 'HOUGANG'), ('QUEENSTOWN', 'QUEENSTOWN'), ('JURONG EAST', 'JURONG EAST'), ('JURONG WEST', 'JURONG WEST'), ('KALLANG', 'KALLANG'), ('MARINE PARADE', 'MARINE PARADE'), ('PASIR RIS', 'PASIR RIS'), ('PUNGGOL', 'PUNGGOL'), ('SEMBAWANG', 'SEMBAWANG'), ('SENGKANG', 'SENGKANG'), ('SERANGOON', 'SERANGOON'), ('TAMPINES', 'TAMPINES'), ('TOA PAYOH', 'TOA PAYOH'), ('WOODLANDS', 'WOODLANDS'), ('YISHUN', 'YISHUN')], default='ANG MO KIO', max_length=25),
        ),
    ]
