# Generated by Django 3.1 on 2020-10-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_auto_20200927_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='gallery_image_0',
            field=models.ImageField(blank=True, default='default_home.png', upload_to='home_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='gallery_image_1',
            field=models.ImageField(blank=True, default='default_home.png', upload_to='home_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='gallery_image_2',
            field=models.ImageField(blank=True, default='default_home.png', upload_to='home_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='gallery_image_3',
            field=models.ImageField(blank=True, default='default_home.png', upload_to='home_images'),
        ),
    ]
