# Generated by Django 3.1 on 2020-10-28 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_auto_20201028_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postal_code',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
